initial code commit
distributed-system-analysis/pbench-ansible-collections pull request #1
Opened 2022-05-12 12:11 UTC by vishalvvr

#### Did:
- add all ansible collection source files
- add ansible-lint.yml & yml_lint_config files for bypassing  unnecessary linting errors
  and warning
- add GitHub action to test and push collection into ansible-galaxy

#### Note: 
Before merging this PR you need the following environment in place
- Add the ansible-galaxy API key into [GitHub secrets](https://github.com/distributed-system-analysis/pbench-ansible-collections/settings/secrets/actions) with the secret key name GALAXY_API_KEY.
- This codebase and GitHub action should be part of the "agent" branch, since we don't have it in our repo I am pushing it into this branch.

2022-05-12 16:22 UTC, webbnh reviewed
Are we sure that we want this stuff in its own repo?  It doesn't have any version/branch-specific dependencies?

2022-05-12 16:22 UTC, webbnh commented on README.md
> +    https://github.com/distributed-system-analysis/pbench/blob/master/agent/ansible/pbench_agent_install.yml
References to "master" appear to redirect to "main", so we should presumably use the latter, here and elsewhere.

2022-05-12 21:23 UTC, portante commented
> Are we sure that we want this stuff in its own repo?

In the past I had understood that the GitHub integration with Ansible Galaxy required one namespace per repository.

But reading about Ansible Collections, that does not seem to be the case.

Can we get a good description for why this needs to be in a separate repository?

2022-05-12 21:23 UTC, portante requested changes
We need to be sure it is a requirement for this ansible galaxy collections work be located in a separate repository.

2022-05-13 09:29 UTC, vishalvvr commented
> Are we sure that we want this stuff in its own repo? It doesn't have any version/branch-specific dependencies?

This ansible collection does not use anything from the pbench source tree, so we are good to separate the collection source from the existing tree.

2022-05-13 09:51 UTC, vishalvvr commented
> > Are we sure that we want this stuff in its own repo?
> 
> In the past I had understood that the GitHub integration with Ansible Galaxy required one namespace per repository.
> 
> But reading about Ansible Collections, that does not seem to be the case.
>
yes, the ansible collection does not have any repo restriction, we just need to add the galaxy API key in GitHub secrets that's it.
   
> Can we get a good description for why this needs to be in a separate repository?

If we add GitHub action( to test, build and push to galaxy) to the existing pbench source tree, GitHub action won't be able to identify whether changes made are in the ansible collection source or pbench source.

After discussion with @ndokos we came to the conclusion that we should create a separate repo to simplify things.

But now I realize that the better approach would be to create a new branch(for the pbench-agent ansible collection) in the pbench repo itself.

2022-05-13 19:31 UTC, webbnh requested changes
I have nits and questions.

2022-05-13 19:31 UTC, webbnh commented on galaxy.yml
> +repository: http://github.com/distributed-system-analysis/pbench
What is this used for?

2022-05-13 19:31 UTC, webbnh commented on galaxy.yml
> +homepage: http://github.com/distributed-system-analysis/pbench/agent
This URL yields a 404.

2022-05-13 19:31 UTC, webbnh commented on galaxy.yml
> +issues: http://github.com/distributed-system-analysis/pbench/issues
This URL yields a 404.

2022-05-13 19:31 UTC, webbnh commented on galaxy.yml
> +documentation: https://distributed-system-analysis.github.io/pbench/doc/
This URL yields a 404.

2022-05-13 19:31 UTC, webbnh commented on roles/pbench_agent_config/tasks/main.yml
> +    source: "{{ pbench_config_url }}"
Where/how is `pbench_config_url` defined, and what does it get defined to?  (Is it going to pull a file from the pbench Git repo?...if os, which _branch_ is it going to reference?)

2022-05-13 19:39 UTC, webbnh commented
> the better approach would be to create a new branch(for the pbench-agent ansible collection) in the pbench repo itself.

I doubt that that would be a better approach:  I think that creates confusion for anyone who is trying to access this content ("Why, when I get the `main` or default branch, can't I find the ansible collection??"), and it denies us the flexibility and power of using multiple branches for development.  That is, relative to putting it on the `main` branch or in its own repo, I think that's the worst of the three options.

> If we add GitHub action( to test, build and push to galaxy) to the existing pbench source tree, GitHub action won't be able to identify whether changes made are in the ansible collection source or pbench source.

Unless the proposed Action is very expensive (or there is some other downside to running it unnecessarily), I don't think this is a real problem.  We don't submit things to the `main` branch (or the release branches) very often, so I don't think unnecessary runs will be an issue.  On the other hand, if it _is_ an issue, it shouldn't be too hard to add some intelligence to the Action to skip the run if the changes aren't pertinent.

2022-11-03 20:11 UTC, portante commented
We finalized that the ansible collections for the Pbench Agent are kept with the Pbench Agent code.

2022-11-03 20:11 UTC, closed without merging